apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kaniko-pipeline-run1
spec:
  pipelineRef:
    name: kaniko-pipeline1
  params:
    - name: git_revision
      value: HEAD
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 100m
